nsert into kittens (kitten_name, week_day, duration) values ('Whiskers', 'Monday', 4);
insert into kittens (kitten_name, week_day, duration) values ('Jo', 'Monday',2);
insert into kittens (kitten_name, week_day, duration) values ('Rocky', 'Tuesday',6);
insert into kittens (kitten_name, week_day, duration) values ('Sox', 'Tuesday',8);
insert into kittens (kitten_name, week_day, duration) values ('Google', 'Tuesday', 3);
insert into kittens (kitten_name, week_day, duration) values ('Garfield', 'Thursday',2);
insert into kittens (kitten_name, week_day, duration) values ('Mittens', 'Thursday',4);
insert into kittens (kitten_name, week_day, duration) values ('Kitty', 'Saturday', 7);
insert into kittens (kitten_name, week_day, duration) values ('Boots', 'Saturday', 2);
insert into kittens (kitten_name, week_day, duration) values ('Tiger', 'Saturday', 5);